  image: php:7.4.20

  test:
    script:
      - apt-get update -yqq
      - apt-get install git -yqq
      - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.5.20.phar
      - chmod +x /usr/local/bin/phpunit
      - pecl install xdebug-2.9.8
      - docker-php-ext-enable xdebug
      - echo "date.timezone = Europe/Warsaw" > /usr/local/etc/php/php.ini
      - cd tests/
      - phpunit --coverage-html /builds/ahmad.abid/php-mvc/tests/coverage/
    artifacts:
      paths:
        - /builds/ahmad.abid/php-mvc/tests/coverage/

  documentation:
    script:
      - curl --location --output /usr/local/bin/phpDocumentor https://phpdoc.org/phpDocumentor.phar
      - chmod +x /usr/local/bin/phpDocumentor
      - cd phpdoc/
      - phpDocumentor
    artifacts:
      paths:
        - /builds/ahmad.abid/php-mvc/phpdoc/docs/

  pages:
    stage: deploy
    dependencies:
      - test
      - documentation
    script:
      - mv /builds/ahmad.abid/php-mvc/tests/coverage/ public/
      - mv /builds/ahmad.abid/php-mvc/phpdoc/docs/ public/
    artifacts:
      paths:
        - public
      expire_in: 30 days
